### ISSUE TITLE
Some errors on Ubuntu

### ISSUE THREAD

**Issue by cipher387** [JagdishPatil2111/OverwatchINT#10]
Traceback (most recent call last):
  File "OverwatchINT.py", line 2, in <module>
    import WebVulture.WebVulture as wv
  File "/workspace/OverwatchINT/WebVulture/WebVulture.py", line 1, in <module>
    from tkinter import *
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by jagdishpatil2111** [comment]
Try installing those libraries. I will make changes in the requirement.txt.
